### PR TITLE
Fix typo for horizontal aperture in vision sensor obs space

### PR DESCRIPTION
**Pull request by sai-prasanna**

### CODE REVIEW

**Review by cremebrule — APPROVED** [review]
LGTM! Thanks for posting this fix!

**Comment by cremebrule** [comment]
Thanks for putting this fix together @sai-prasanna ! Would you mind changing the target branch to `StanfordVL/og-develop`? We don't allow directly merges into our main branch and instead simply sync it periodically with our `og-develop` branch during releases.

**Comment by sai-prasanna** [comment]
@cremebrule Changed it!

**Review by cremebrule — APPROVED** [review]
LGTM!

**Comment by cremebrule** [comment]
awesome, thanks! merged

**Pull request merged**
